version: "3.9"

name: your-cast

services:
  web:
    container_name: podcasts_web
    image: your-cast/account:1.0.0
    ports:
      - "8001:80"

  nginx:
    container_name: podcasts_nginx
    image: nginx:1.24
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d/
      - ./src/:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
      - web
      - database

  database:
    container_name: podcasts_database
    image: postgres:13.10
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - local-database:/var/lib/postgresql/data

  php:
    container_name: podcasts_php
    build:
      args:
        user: podcast
        uid: 1000
      context: .docker/php
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./src/:/var/www/html

  redis:
    container_name: podcasts_redis
    build:
      context: .docker/redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 150M
        reservations:
          cpus: 0.25
          memory: 120M
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - local-redis:/data

volumes:
  local-database:
    driver: local
  local-redis:
    driver: local
