version: '3.8'

services:
  web:
    container_name: podcasts_nginx
    image: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - php
      - database
  php: &app-podcasts-service
    container_name: podcasts_php
    build:
      args:
        user: podcast
        uid: 1000
      context: .docker/php
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./src/:/var/www/html
  scheduler:
    <<: *app-podcasts-service
    container_name: podcasts_scheduler
    restart: always
    command: /scheduler/scheduler.sh
  database:
    container_name: podcasts_database
    image: postgres:13.1
    environment:
      POSTGRES_DB: yourcast
      POSTGRES_USER: yourcast
      POSTGRES_PASSWORD: mysecretpassword123!#
    ports:
      - '5432:5432'
    volumes:
      - postgres-database-podcasts:/var/lib/postgresql/data
  redis:
    container_name: podcasts_redis
    build:
      context: .docker/redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-podcasts:/data
  elasticsearch:
    container_name: podcasts_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
    volumes:
      - elastic-podcasts:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    depends_on:
      - php
  kibana:
    container_name: podcasts_kibana
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch

volumes:
  postgres-database-podcasts:
    driver: local
  redis-podcasts:
    driver: local
  elastic-podcasts:
    driver: local
