version: '3.2'

services:
  web:
    container_name: podcasts_nginx
    image: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - php
      - database
  #      - redis

  php: &app-podcasts-service
    container_name: podcasts_php
    build:
      args:
        user: podcast
        uid: 1000
      context: .docker/php
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./src/:/var/www/html

#  queue:
#    <<: *app-podcasts-service
#    container_name: podcasts_queue
#    restart: always
#    command: php /var/www/html/artisan queue:work

  scheduler:
    <<: *app-podcasts-service
    container_name: podcasts_scheduler
    restart: always
    command: /scheduler/scheduler.sh

  database:
    container_name: podcasts_database
    image: postgres:latest
    environment:
      POSTGRES_DB: yourcast
      POSTGRES_USER: yourcast
      POSTGRES_PASSWORD: mysecretpassword123!#
    ports:
      - "5432:5432"
    volumes:
      - postgres-database-podcasts:/var/lib/postgresql/data

#  zookeeper:
#    container_name: your-cast_zookeeper
#    image: confluentinc/cp-zookeeper:latest
#    ports:
#      - '2181:2181'
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#
#  kafka:
#    container_name: your-cast_kafka
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    ports:
#      - '29092:29092'
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  clickhouse:
#    container_name: podcasts_clickhouse
#    image: yandex/clickhouse-server:latest
#    ports:
#      - '8123:8123'
#      - '9000:9000'
#    volumes:
#      - clickhouse-database-podcasts:/var/lib/clickhouse

#  redis:
#    container_name: podcasts_redis
#    build: .docker/redis
#    restart: always
#    ports:
#      - '6379:6379'
#    volumes:
#      - redis-podcasts:/data

volumes:
  postgres-database-podcasts:
    driver: local
#  clickhouse-database-podcasts:
#    driver: local
#  redis-podcasts:
#    driver: local
