export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SHOW_CREATE_STEP_FIRST = 'SHOW_CREATE_STEP_FIRST';
export const SHOW_CREATE_STEP_SECOND = 'SHOW_CREATE_STEP_SECOND';
export const SHOW_INNER = 'SHOW_INNER';
export const SHOW_LIST = 'SHOW_LIST';
